### ISSUE TITLE
Animation & Position

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/cover-element#1]
Hi

Love your cover-element.

My shutter positions have long decimal numbers. Is there any way to truncate this?

Also, it would be nice for the element to reflect the actual position. Animation would be perfect.

Thank you.
![Screen Shot 2019-10-14 at 15 16 32](https://user-images.githubusercontent.com/34303331/66754150-a195d600-ee95-11e9-86a7-d2643d232177.png)

```
type: picture-elements
image: /local/
elements:
  - type: 'custom:cover-element'
    entity: cover.sitting_room_door_shutter
    position_label:
      show: true
      open_text: open
      closed_text: closed
      interim_text: part open
    style:
      top: 50%
      height: 100%
      background-color: 'rgba(255, 255, 255, 0.6)'
      width: 50%
      border-radius: 10px
      left: 50%

```
